### ISSUE TITLE
ENE - ENE's Not Excel

### ISSUE THREAD

**Issue by abarichello** [caravelahc/projetos#22]
O projeto consiste em criar um simples site em Elm para expor os csv's obtidos através do site do governo e-Sic, tais documentos contém dados de aprovações/fi/reprovações e notas de alunos em disciplinas do INE. 
Tal site pode ser extendido para suportar outros grupos de graduação desde que o CSV fornecido siga o mesmo padrão dos anteriores.

[Canal rocket chat](https://chat.caravela.club/channel/ene-ufsc)

**Comment by abarichello** [comment]
ENE tá completo, o que falta agora é só dados mesmo. 
Falta também o pessoal da gestão da UFSC colaborar e responder direitos os pedidos do e-SIC.
https://github.com/caravelahc/ene

**Comment by ranisalt** [comment]
Coloca um passo a passo de como pedir esses dados pelo e-SIC, com o texto padrão e tal.
